name: Manual
on:
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        default: Hello
        required: true
        description: Message

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{vars.USERNAME}}
    steps:
      - run: echo "${USER}"
